apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main,master]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: my-application
    appstudio.openshift.io/component: sample-go
    build.appstudio.openshift.io/component: sample-go
    pipelines.appstudio.openshift.io/type: build
  name: sample-go-on-pull-request
  namespace: karthik-jk
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-appstudio/user-workload:on-pr-{{revision}}
  - name: dockerfile
    value: https://raw.githubusercontent.com/karthikjeeyar/sample-go-repo/main/docker/Dockerfile
  pipelineRef:
    bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
    name: docker-build
  workspaces:
  - name: workspace
    persistentVolumeClaim:
      claimName: appstudio
    subPath: sample-go-on-pull-request-{{revision}}
  - name: registry-auth
    secret:
      secretName: redhat-appstudio-registry-pull-secret
status: {}
